"use client";
import {useMemo,useState} from "react";
import {Heart,Download,Search} from "lucide-react";
const wallpapers=[
{id:1,title:"Mountain Night",cat:"Nature",url:"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=900&q=85"},
{id:2,title:"Neon City",cat:"City",url:"https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=900&q=85"},
{id:3,title:"Ocean Calm",cat:"Nature",url:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85"},
{id:4,title:"Purple Abstract",cat:"Abstract",url:"https://images.unsplash.com/photo-1557682250-33bd709cbe85?auto=format&fit=crop&w=900&q=85"},
{id:5,title:"Minimal Lines",cat:"Minimal",url:"https://images.unsplash.com/photo-1557683316-973673baf926?auto=format&fit=crop&w=900&q=85"},
{id:6,title:"Forest Road",cat:"Nature",url:"https://images.unsplash.com/photo-1448375240586-882707db888b?auto=format&fit=crop&w=900&q=85"}];
export default function Home(){const[c,setC]=useState("All");const[q,setQ]=useState("");const[f,setF]=useState<number[]>([]);const list=useMemo(()=>wallpapers.filter(w=>(c==="All"||w.cat===c)&&w.title.toLowerCase().includes(q.toLowerCase())),[c,q]);return <main><div className="wrap"><nav className="nav"><div className="brand">Wallpaper<span>.app</span></div><div className="navlinks"><span>Popular</span><span>Categories</span><span>Favorites ♥ {f.length}</span></div></nav><section className="hero"><h1>Find your next wallpaper.</h1><p>Beautiful wallpapers made for your phone.</p><div className="search"><Search size={22}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search wallpapers..."/><button>Search</button></div></section><div className="cats">{["All","Nature","City","Abstract","Minimal"].map(x=><button key={x} onClick={()=>setC(x)} className={"cat "+(c===x?"active":"")}>{x}</button>)}</div><section className="grid">{list.map(w=><article className="card" key={w.id}><div className="thumb" style={{backgroundImage:"url('"+w.url+"')"}}/><div className="info"><b>{w.title}</b><div className="actions"><button className="icon" onClick={()=>setF(v=>v.includes(w.id)?v.filter(x=>x!==w.id):[...v,w.id])}><Heart size={18} fill={f.includes(w.id)?"currentColor":"none"}/></button><a className="icon" href={w.url+"&dl=1"} target="_blank" rel="noreferrer"><Download size={18}/></a></div></div></article>)}</section><footer className="footer">© 2026 Wallpaper.app · Made for mobile</footer></div></main>}